language: python

python:
    - 2.6
    - 2.7
    - pypy
    - 3.2
    - 3.3
    - 3.4

install:
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install psycopg2ct tornado; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install psycopg2 unittest2 tornado; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install psycopg2 tornado; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install psycopg2 tornado; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install psycopg2 tornado; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install psycopg2 tornado; fi

script: nosetests
