language: python
python:
- 2.6
- 2.7
- pypy
- 3.2
- 3.3
- 3.4
addons:
  postgresql: '9.3'
install:
- if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
- if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install -r requirements.pip;
  fi
- if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install -r requirements.pypy;
  fi
script: nosetests --with-coverage --cover-package=queries --verbose
after_success:
- coveralls
deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  on:
    python: 2.7
    tags: true
    all_branches: true
  user: crad
  password:
    secure: UWQWui+QhAL1cz6oW/vqjEEp6/EPn1YOlItNJcWHNOO/WMMOlaTVYVUuXp+y+m52B+8PtYZZCTHwKCUKe97Grh291FLxgd0RJCawA40f4v1gmOFYLNKyZFBGfbC69/amxvGCcDvOPtpChHAlTIeokS5EQneVcAhXg2jXct0HTfI=
