language: python

python:
    - 2.6
    - 2.7
    - pypy
    - 3.2
    - 3.3
    - 3.4

install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
    - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install -r requirements.pip; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install -r requirements.pypy; fi

script: nosetests --with-coverage --cover-package=queries

after_success:
  - coveralls